
name: deploy-workflow
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://studentsunion.cusat.ac.in/git/pull/'
        method: 'GET'
    
